[package]
name = "rt"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = { version = "0.9.20", features = ["derive", "dull-color"] }
thiserror = "2.0.17"
which = "8.0.0"
inquire = "0.9.1"

[dev-dependencies]
tempfile = "3.24.0"
